services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  redis:
    driver: local
